### ISSUE TITLE
1.20.1 forge/ oculus and rubidium animation bug

### ISSUE THREAD

**Issue by Jabkkm** [bernie-g/geckolib#519] opened 2023-11-18 23:28 UTC
geckolib v4.2.4 causes models of mobs to stand still even when they're moving(no animations at all) when shaders with "entity shadows" option turned on. I tried complementary shaders and BSL shaders, they have the same issue, so i tried to downgrade gecklib to 4.2.1, the animations came back.

**Comment by Tslat** [comment] 2023-11-18 23:57
Duplicate of #512

**Closed by Tslat** 2023-11-18 23:57 UTC
