### ISSUE TITLE
crash randomly when exploring

### ISSUE THREAD

**Issue by AdnanuReeves** [bernie-g/geckolib#81] opened 2021-01-23 14:09 UTC
latest 1.16.5 version
https://paste.ubuntu.com/p/Q46mmgN8yw/

**Comment by AdnanuReeves** [comment] 2021-01-23 14:50
Works fine downgrading to 3.0.0

**Comment by AzureDoom** [comment] 2021-01-23 17:08
It will still work with latest as well, it's just a randomly bug is random and unable to reproduced in a working manner. @baileyholl it's doing it again, I don't think the fix worked.

**Comment by AzureDoom** [comment] 2021-01-30 21:50
Confirmed fix in latest release.

**Comment by AzureDoom** [comment] 2021-01-30 21:50
whoops wrong issue. Stupid phone

**Comment by AzureDoom** [comment] 2021-02-04 15:45
Alright a possible fix has been pushed again to v3.0.12. Please let us know if it happens again.

**Comment by AzureDoom** [comment] 2021-03-28 03:44
No new errors sent about this. Closing as it seems was fixed.

**Closed by AzureDoom** 2021-03-28 03:44 UTC
