### ISSUE TITLE
Optifine Emissive Entity textures don't Render

### ISSUE THREAD

**Issue by Pierconic** [bernie-g/geckolib#505] opened 2023-10-12 16:30 UTC
Using the latest version of Geckolib, emissive entity textures provided by resource packs do not render, regardless of whether the entity is a Geckolib animated entity. (Other emissives- items, blocks, particles, etc; still work as intended.) I have tested this with only Geckolib installed, and with several different resource packs, as well as older versions of Optifine. 
Geckolib entities with built in emissive textures still work fine, it's only emissives added by optifine-compatible resource packs that aren't rendering.

**Comment by Tslat** [comment] 2023-10-12 19:55
Is this a duplicate of https://github.com/bernie-g/geckolib/issues/493 ?

**Comment by Pierconic** [comment] 2023-10-12 23:40
No, this specifically regards textures with optifine's emissive property. Reflections may be related though? I'm pretty sure reflections are shader based, but if they're run through Optifine, it may be the same issue.

**Comment by 909oce** [comment] 2023-10-16 23:25
I'm also still facing this issue after testing the version where changelog noted "possibly fixed". Emissives are buggy and reflections still don't work. For me particles like XP orbs should be emissive but aren't and armor isn't reflective.

**Comment by Tslat** [comment] 2023-10-17 00:25
Yeah the fix didn't work

Unfortunately optifine is historically impossible to work with, and it is intentionally obfuscated preventing people from easily debugging it
This is an ultra-low priority because of these factors, but if I can think of a solution I'll try it again

**Comment by 909oce** [comment] 2023-10-17 00:54
Oh I mean I don't even use Optifine, I'm on Sodium + Iris if that makes a difference.

**Closed** 2023-10-26 11:09 UTC
Labels: bug
